import * as THREE from 'three';
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
gsap.registerPlugin(ScrollTrigger);
const canvas=document.querySelector('#webgl'),root=document.documentElement,reduceMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(34,1,.1,100);camera.position.set(0,.1,6.8);
const renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;
scene.add(new THREE.HemisphereLight(0xf8eee3,0x090706,2.5));const key=new THREE.DirectionalLight(0xffe8d2,4.5);key.position.set(4,5,6);scene.add(key);const fill=new THREE.DirectionalLight(0x9e7a62,2.2);fill.position.set(-4,1,3);scene.add(fill);const rim=new THREE.PointLight(0xd6a25c,42,14,2);rim.position.set(-3,2,4);scene.add(rim);
const rig=new THREE.Group();rig.position.set(1.45,.25,0);rig.rotation.set(-.08,-.22,.08);scene.add(rig);
const matte=new THREE.MeshPhysicalMaterial({color:0x151311,roughness:.25,metalness:.52,clearcoat:.75}),black=new THREE.MeshPhysicalMaterial({color:0x050505,roughness:.16,metalness:.82,clearcoat:.8}),glass=new THREE.MeshPhysicalMaterial({color:0x07131a,roughness:.06,metalness:.18,transmission:.18,clearcoat:1}),brass=new THREE.MeshStandardMaterial({color:0xd4a25b,roughness:.23,metalness:.92}),rubber=new THREE.MeshStandardMaterial({color:0x080807,roughness:.7});
function m(g,mat,p=[0,0,0],r=[0,0,0]){const x=new THREE.Mesh(g,mat);x.position.set(...p);x.rotation.set(...r);rig.add(x);return x}
m(new THREE.BoxGeometry(2.65,1.58,1.34),matte);m(new THREE.BoxGeometry(2.3,1.2,1.45),rubber,[0,-.03,-.72]);m(new THREE.BoxGeometry(1.22,.42,.82),matte,[-.1,1,0]);m(new THREE.BoxGeometry(.7,.26,.42),black,[-.1,1.32,0]);m(new THREE.BoxGeometry(.5,.18,.36),glass,[-.1,1.5,.02]);m(new THREE.BoxGeometry(.62,1.85,.72),rubber,[-.88,-.25,.03],[.08,0,-.12]);m(new THREE.BoxGeometry(.1,1.2,.46),matte,[-1.2,-.25,.03],[.08,0,-.12]);m(new THREE.CylinderGeometry(.48,.48,.28,64),brass,[.86,-.05,-.02],[0,0,Math.PI/2]);m(new THREE.CylinderGeometry(.38,.38,.31,64),black,[1,-.05,-.02],[0,0,Math.PI/2]);m(new THREE.CylinderGeometry(.68,.78,1.35,64),black,[1.38,-.05,-.02],[0,0,Math.PI/2]);const focus=m(new THREE.TorusGeometry(.73,.095,18,64),brass,[1.58,-.05,-.02],[0,Math.PI/2,0]);m(new THREE.TorusGeometry(.67,.055,18,64),brass,[1.82,-.05,-.02],[0,Math.PI/2,0]);m(new THREE.CylinderGeometry(.61,.61,.16,64),black,[2.02,-.05,-.02],[0,0,Math.PI/2]);m(new THREE.CylinderGeometry(.5,.5,.035,64),glass,[2.11,-.05,-.02],[0,0,Math.PI/2]);
const iris=new THREE.Group();iris.position.set(2.135,-.05,-.02);iris.rotation.z=Math.PI/2;rig.add(iris);for(let i=0;i<9;i++){const b=new THREE.Mesh(new THREE.BoxGeometry(.22,.035,.11),brass);b.position.set(Math.cos(i*Math.PI*2/9)*.25,Math.sin(i*Math.PI*2/9)*.25,.02);b.rotation.z=i*Math.PI*2/9;iris.add(b)}
for(let i=0;i<3;i++)m(new THREE.CylinderGeometry(.15+i*.025,.15+i*.025,.1,32),brass,[-.5+i*.38,.87,.35],[Math.PI/2,0,0]);m(new THREE.CylinderGeometry(.1,.1,.08,32),brass,[.66,.85,.42],[Math.PI/2,0,0]);m(new THREE.BoxGeometry(.36,.08,.28),brass,[.15,1.2,0]);m(new THREE.BoxGeometry(.78,.48,.06),glass,[-.45,-.25,.69]);
const frames=new THREE.Group();scene.add(frames);const fm=new THREE.MeshBasicMaterial({color:0xd6a25c,transparent:true,opacity:.26,wireframe:true});for(let i=0;i<7;i++){const f=new THREE.Mesh(new THREE.BoxGeometry(1.15+i*.08,.72+i*.05,.015),fm);f.position.set(-3.4+i*1.1,.4+Math.sin(i)*.7,-1.2-i*.25);f.rotation.set(.12*i,-.15+i*.08,-.1*i);frames.add(f)}
const dg=new THREE.BufferGeometry(),dc=1500,dp=new Float32Array(dc*3);for(let i=0;i<dc;i++){dp[i*3]=(Math.random()-.5)*14;dp[i*3+1]=(Math.random()-.5)*8;dp[i*3+2]=(Math.random()-.5)*11-2}dg.setAttribute('position',new THREE.BufferAttribute(dp,3));const dust=new THREE.Points(dg,new THREE.PointsMaterial({color:0xe6c28f,size:.009,transparent:true,opacity:.42,depthWrite:false}));scene.add(dust);
const portal=new THREE.Mesh(new THREE.RingGeometry(.55,1.12,64),new THREE.MeshBasicMaterial({color:0xd6a25c,transparent:true,opacity:0,side:THREE.DoubleSide}));portal.position.set(2.16,-.05,-.02);portal.rotation.y=Math.PI/2;rig.add(portal);
const s={px:0,py:0,tx:0,ty:0,velocity:0};let last=scrollY;addEventListener('scroll',()=>{s.velocity=scrollY-last;last=scrollY},{passive:true});addEventListener('pointermove',e=>{s.tx=(e.clientX/innerWidth-.5)*.65;s.ty=(e.clientY/innerHeight-.5)*.45});
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}resize();addEventListener('resize',resize,{passive:true});
if(!reduceMotion){gsap.fromTo('.hero-copy > *',{y:38,opacity:0},{y:0,opacity:1,duration:1.2,stagger:.1,ease:'power4.out',delay:.2});gsap.to(frames.rotation,{y:-Math.PI*2,duration:42,repeat:-1,ease:'none'});
const tl=gsap.timeline({scrollTrigger:{trigger:'#experience',start:'top top',end:'bottom bottom',scrub:1.15}});tl.to(rig.position,{x:-1.1,y:.5,z:-.4,ease:'none'},0).to(rig.rotation,{x:.42,y:-1.05,z:-.32,ease:'none'},0).to(camera.position,{z:5.1,y:.7,ease:'none'},0).to(rig.scale,{x:.8,y:.8,z:.8,ease:'none'},.25).to(rig.position,{x:1.55,y:-.45,z:-.9,ease:'none'},.5).to(rig.rotation,{x:-.25,y:1.2,z:.25,ease:'none'},.5).to(camera.position,{z:4.4,y:-.2,ease:'none'},.5).to(rig.scale,{x:1.15,y:1.15,z:1.15,ease:'none'},.72).to(rig.position,{x:0,y:0,z:0,ease:'none'},.72).to(rig.rotation,{x:.1,y:-.25,z:0,ease:'none'},.72);
const pt=gsap.timeline({scrollTrigger:{trigger:'#portal',start:'top bottom',end:'center center',scrub:1}});pt.fromTo('.portal-card',{scale:.72,rotate:-7,borderRadius:'50%',filter:'brightness(.45)'},{scale:1,rotate:-2,borderRadius:'0%',filter:'brightness(1)',ease:'none'}).to(portal.material,{opacity:.65,ease:'none'},0).to(rig.position,{x:-.3,z:-.65,ease:'none'},0).to(rig.rotation,{y:-.7,z:.16,ease:'none'},0).to(camera.position,{z:4.7,ease:'none'},0);
gsap.utils.toArray('.reveal').forEach(el=>gsap.fromTo(el,{y:70,opacity:0},{y:0,opacity:1,duration:1,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 86%',toggleActions:'play none none reverse'}}));gsap.utils.toArray('.story-card').forEach((c,i)=>gsap.fromTo(c,{yPercent:i%2?16:9,scale:.9,opacity:.45},{yPercent:0,scale:1,opacity:1,ease:'none',scrollTrigger:{trigger:c,start:'top bottom',end:'center center',scrub:true}}));ScrollTrigger.refresh()}
function render(t){requestAnimationFrame(render);const time=t*.001;s.px+=(s.tx-s.px)*.035;s.py+=(s.ty-s.py)*.035;if(!reduceMotion){rig.rotation.x+=(s.py*.24-rig.rotation.x)*.018;rig.rotation.z+=(-s.px*.12-rig.rotation.z)*.018;focus.rotation.z+=.004;iris.rotation.x=Math.sin(time*1.2)*.08;portal.scale.setScalar(1+Math.sin(time*1.5)*.035);dust.rotation.y=time*.008;dust.position.y=Math.sin(time*.12)*.12;root.style.setProperty('--scroll-velocity',Math.min(Math.abs(s.velocity)/80,1).toFixed(3));s.velocity*=.9}renderer.render(scene,camera)}requestAnimationFrame(render);
